
exports.dataArray = [
  {itemName: 'Force of Nature', combo: ['spatula', 'spatula'], description: 'Gain +1 team size'},
  {itemName: 'Blade of the Ruined King', combo: ['spatula', 'recurvebow'], description: 'Wearer is also a Blademaster'},
  {itemName: 'Bloodthirster', combo: ['bfsword', 'negatroncloak'], description: 'Attacks heal for 50% of damage'},
  {itemName: 'Cursed Blade', combo: ['negatroncloak', 'recurvebow'], description: 'Attacks have a 20% chance to Shrink (-1 enemy star, down to level 0)'},
  {itemName: 'Darkin', combo: ['spatula', 'tearofthegoddess'], description: 'Wearer is also a Demon'},
  {itemName: 'Dragon\'s Claw', combo: ['negatroncloak', 'negatroncloak'], description: '83% resistance to magic damage'},
  {itemName: 'Frozen Heart', combo: ['tearofthegoddess', 'chainvest'], description: 'Adjacent enemies lose 25% Attack Speed'},
  {itemName: 'Frozen Mallet', combo: ['spatula', 'giantsbelt'], description: 'Wearer is also a Glacial'},
  {itemName: 'Guardian Angel', combo: ['bfsword', 'chainvest'], description: 'Revives champ with 800 HP after 2 second'},
  {itemName: 'Guinsoo\'s Rageblade', combo: ['needlesslylargerod', 'recurvebow'], description: 'Attacks give 5% Attack Speed. Stacks infinitely'},
  {itemName: 'Hextech Gunblade', combo: ['bfsword', 'needlesslylargerod'], description: 'Heal for 33% of all damage dealt'},
  {itemName: 'Hush', combo: ['tearofthegoddess', 'negatroncloak'], description: 'Attacks have a 50% chance to Silence for 3 seconds'},
  {itemName: 'Infinity Edge', combo: ['bfsword', 'bfsword'], description: 'Critical Strikes deal +150% damag'},
  {itemName: 'Ionic Spark', combo: ['negatroncloak', 'needlesslylargerod'], description: 'Whenever an enemy casts a spell they take 150 true damage'},
  {itemName: 'Knights Vow', combo: ['spatula', 'chainvest'], description: 'Wearer is also a Knight'},
  {itemName: 'Locket of the Iron Solari', combo: ['needlesslylargerod', 'chainvest'], description: 'On start of combat, allies 2 spaces to the left and right gain 250 shield for 4s'},
  {itemName: 'Luden\'s Echo', combo: ['needlesslylargerod', 'tearofthegoddess'], description: 'Deal 200 splash damage on ability hit'},
  {itemName: 'Morellonomicon', combo: ['needlesslylargerod', 'giantsbelt'], description: 'Spells burn for 4% of max HP per second and disable healing'},
  {itemName: 'Phantom Dancer', combo: ['chainvest', 'recurvebow'], description: 'Wearer dodges all Critical Strikes (including ability crits)'},
  {itemName: 'Rabadon\'s Deathcap', combo: ['needlesslylargerod', 'needlesslylargerod'], description: 'Wearer\'s Ability Damage increased by 50%'},
  {itemName: 'Rapid Firecannon', combo: ['recurvebow', 'recurvebow'], description: 'Attacks cannot be dodged. Attack Range is doubled'},
  {itemName: 'Red Buff', combo: ['chainvest', 'giantsbelt'], description: 'Attacks burn for 13% of max HP over 5s and disable healing'},
  {itemName: 'Redemption', combo: ['tearofthegoddess', 'giantsbelt'], description: 'At 25% health heal all nearby allies for 1000 HP'},
  {itemName: 'Runaan\'s Hurricane', combo: ['spatula', 'negatroncloak'], description: 'Attacks hit 1 additional enemy. This extra hit does 75% damage and applies on-hit effects'},
  {itemName: 'Seraph\'s Embrace', combo: ['tearofthegoddess', 'tearofthegoddess'], description: 'Regain 20 mana each time a spell is cast'},
  {itemName: 'Spear of Shojin', combo: ['bfsword', 'tearofthegoddess'], description: 'After casting, gain 15% of max mana per attack'},
  {itemName: 'Statikk Shiv', combo: ['recurvebow', 'tearofthegoddess'], description: 'Every 3rd attack deals 90 splash magical damage to 3 enemies'},
  {itemName: 'Sword Breaker', combo: ['chainvest', 'negatroncloak'], description: 'Attacks have a 25% to disarm'},
  {itemName: 'Sword of the Divine', combo: ['recurvebow', 'bfsword'], description: 'Every 1s gain a 7% chance to gain 100% Critical Strike'},
  {itemName: 'Thornmail', combo: ['chainvest', 'chainvest'], description: 'Reflect 100% of of physical damage mitigated as Magic Damage'},
  {itemName: 'Titanic Hydra', combo: ['giantsbelt', 'recurvebow'], description: 'Attacks deal 10% of the wearer\'s max HP as splash'},
  {itemName: 'Warmog\'s Armor', combo: ['giantsbelt', 'giantsbelt'], description: 'Regenerate 6% max Health per second'},
  {itemName: 'Youmuu\'s Ghostblade', combo: ['spatula', 'bfsword'], description: 'Wearer is also an Assassin'},
  {itemName: 'Yuumi', combo: ['spatula', 'needlesslylargerod'], description: 'Wearer is also a Sorcerer'},
  {itemName: 'Zeke\'s Herald', combo: ['bfsword', 'giantsbelt'], description: 'On start of combat, allies 2 spaces to the left and right gain +15% Attack Speed'},
  {itemName: 'Zephyr', combo: ['negatroncloak', 'giantsbelt'], description: 'On start of combat banish an enemy'}
] 

